import { NextIntlClientProvider } from 'next-intl';
import { Toaster } from "@/components/ui/sonner";
// components
import LocaleLanguageSetter from "@/components/common/locale-lng-setter";
import SmoothScrolling from "@/utils/SmoothScrolling";
import Navbar from '@/components/common/navbar';
import { CartProvider } from '@/context/cart-context';
import { routing } from '@/i18n/routing';
import { SanityLive } from "../../sanity/lib/live";
import { VisualEditing } from "next-sanity/visual-editing";
import { DisableDraftMode } from "../../components/sanity/DisableDraftMode";
import { draftMode } from "next/headers";
import { getNavData } from '@/sanity/getData/getNavData';

export function generateStaticParams() {
    return routing.locales.map((locale) => ({ locale }));
}

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function LocaleLayout({ children, params }) {

    const { locale } = await params;
    const messages = (await import(`../../messages/${locale}.json`)).default;
    const navData = await getNavData(locale);

  return (
        <>
            {(await draftMode()).isEnabled && (
                <>
                    <DisableDraftMode />
                    <VisualEditing />
                </>
            )}
            <NextIntlClientProvider messages={messages} locale={locale}>
                <CartProvider>
                <SmoothScrolling>
                    <LocaleLanguageSetter locale={locale} />
                    <Navbar categoryGroups={navData.categoryGroups} navBundles={navData.bundles} />
                    <main>
                        {children}
                    </main>
                </SmoothScrolling>
                </CartProvider>
                <Toaster richColors toastOptions={{
                    duration: 5000,
                    closeButton: true
                }} />
            </NextIntlClientProvider>
            <SanityLive />
        </>
    );
}
