import { NextIntlClientProvider } from 'next-intl';
import { Toaster } from "@/components/ui/sonner";
// components
import LocaleLanguageSetter from "@/components/common/locale-lng-setter";
import SmoothScrolling from "@/utils/SmoothScrolling";
import Navbar from '@/components/common/navbar';
import Footer from '@/components/common/footer';
// import { VisualEditing } from "next-sanity/visual-editing";
// import { DisableDraftMode } from "../../components/sanity/DisableDraftMode";
// import { draftMode } from "next/headers";
// import { SanityLive } from "../../sanity/lib/live";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function LocaleLayout({ children, params }) {

    const { locale } = await params;
    const messages = (await import(`../../messages/${locale}.json`)).default;

  return (
    // <>
    //     {(await draftMode()).isEnabled && (
    //         <>
    //             <DisableDraftMode />
    //             <VisualEditing />
    //         </>
    //     )}

        <NextIntlClientProvider messages={messages} locale={locale}>
            <SmoothScrolling>
                <LocaleLanguageSetter locale={locale} />
                <div className="max-w-[1920px] mx-auto h-full">
                    <Navbar />
                    <main>
                        {children}
                    </main>
                    <Footer />
                </div>
            </SmoothScrolling>
            <Toaster richColors toastOptions={{
                duration: 5000,
                closeButton: true
            }} />
        </NextIntlClientProvider>
    //     <SanityLive />
    // </>
  );
}
